### ISSUE TITLE
Invalid Login

### ISSUE THREAD

**Issue by jetri12** [jakemadness/gaiaonline-api#1]
When I am changing a account and the Script is enabled, It won't let me login and it always says "Invalid Login, Please Try again" so i need to disabled it first then log in and then enable it again. Is there a way to fix it?

**Comment by iTURTL3** [comment]
This happens when a nonce is generated after logging out, just make sure you don't have multiple tabs open when logged out/logging in

**Comment by jetri12** [comment]
I already tried it but it's still the same. :(
